name:                 BootstrapValidator
highlighter:          pygments

source:               .
destination:          ../bootstrapvalidator.com
markdown:             kramdown
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/

paginate:             5
paginate_path:        /news/page:num
encoding:             UTF-8
relative_permalinks:  false
permalink:            /news/:title/
timezone:             Asia/Ho_Chi_Minh

# Custom variables
# not defined by Jekyll
license:
  developer:
    price:            25$
    #url:              https://gum.co/bv-developer-license
    url:              http://selz.co/1v8tldQ
  organization:
    price:            75$
    #url:              https://gum.co/bv-organization-license
    url:              http://selz.co/1v8tuhB
current_version:      0.5.3
released_date:        2014.11.05
github_watchers:      1376
github_forks:         755
github_downloads:     86,000
twitter_followers:    199
download:
  dist:               https://github.com/nghuuphuoc/bootstrapvalidator/releases/download/v0.5.3/bootstrapvalidator-dist-0.5.3.zip
  tag:                https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.5.3.zip
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/docs
ga_code:              UA-44786951-2
jquery_plugin_url:    http://plugins.jquery.com/bootstrapValidator
disqus:               bootstrapvalidator